# Configuration for deployment from GitHub to server.
name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
    - name: 'Create env file'
      run: |
        touch .env
        echo VITE_API_URL_PROD=https://danielsiberry.com/api >> .env
        echo VITE_SERVER_BUILD=true >> .env
        cat .env
    - run: npm install
    - run: npm run build-server
    - run: cp -r /var/www/runners/actions-runner-blog/_work/blog/blog/dist/. /var/www/blog